### ISSUE TITLE
KeyError: 'network_g'

### ISSUE THREAD

**Issue by quhaoooo** [Srameo/LED#10]
请问这个是怎么回事呢？ 看起来是yaml 不能读子yaml. 
![image](https://github.com/Srameo/LED/assets/99603607/145dbd4e-bba5-463f-ad52-62184827d34e)

**Comment by Srameo** [comment]
您好请问可以看下您的yaml文件以及运行时的命令吗？

**Comment by quhaoooo** [comment]
大佬您好。 
运行命令是这样的：
![image](https://github.com/Srameo/LED/assets/99603607/c5f3edef-0015-4310-a270-7f307783279b)
yaml是这样的：
![image](https://github.com/Srameo/LED/assets/99603607/bd00f2da-5b58-4be1-826b-fc8df8727138)

**Comment by Srameo** [comment]
`scripts/image_process.py` 脚本暂不支持递归的yaml读取。并且传入的yaml文件只需network_g配置即可，您可以将`--network_options`选项更改为`options/base/network_g/unet.yaml`进行测试。

btw, 如果LED对您的项目有帮助的话，希望您可以帮我们点个star🌟，这将是对我们进一步科研的莫大鼓励！感谢！

**Comment by quhaoooo** [comment]
好的大佬，已经可以用了。 非常感谢。
