### ISSUE TITLE
遇到一个缺库问题

### ISSUE THREAD

**Issue by xiexie2001** [Srameo/LED#19]
您好，我在执行Quick Demo的 `python scripts/image_process.py --help` 遇到如下的缺库问题， `bash install.sh` 是正常结束的。请问这个具体是缺什么，有办法解决吗？

(LED-ICCV23) xiexie@xiexie-MSI:~/Project/ICCV23-LED$ python scripts/image_process.py --help
Traceback (most recent call last):
  File "scripts/image_process.py", line 4, in <module>
    import rawpy
  File "/home/xiexie/Project/ICCV23-LED/downloads/rawpy/rawpy/__init__.py", line 5, in <module>
    import rawpy._rawpy
ImportError: libraw.so.23: cannot open shared object file: No such file or directory

**Comment by Srameo** [comment]
您可以参考 https://github.com/Srameo/LED/issues/7#issuecomment-1733200338 中的解决方案

**Comment by xiexie2001** [comment]
好的，执行完`sudo ldconfig`后已解决。
