### ISSUE TITLE
关于测试结果的疑问

### ISSUE THREAD

**Issue by 0getworld** [Srameo/LED#21]
我自己拍了一些raw图数据集，bayer模式是BGGR，也按照作者您提到的数据预处理对数据做了处理，但测试的结果偏绿，请问下这可能是什么原因导致的呢？
![s33_20231029150511_0 055425s raw_85383](https://github.com/Srameo/LED/assets/78095525/97f17fa1-0aa3-46b4-af71-c1f7d7a318f8)
原gt图
![JPG_VI_20231029150043](https://github.com/Srameo/LED/assets/78095525/9742db80-6a4f-40d5-89c4-0c40bce974e9)
lq图
![JPG_VI_20231029150043](https://github.com/Srameo/LED/assets/78095525/191779f4-7679-45a5-b5d3-d7ffb2af0015)

**Comment by Srameo** [comment]
请问您预处理数据的具体步骤以及代码可以分享一下嘛？感觉像是预处理时出现了问题。

另外请问您测试用的模型是什么呢？如果您的相机型号不包含在我们公开的模型中，则您需要首先对您自己的数据集进行finetune。使用finetune后的网络进行测试

**Comment by 0getworld** [comment]
> 请问您预处理数据的具体步骤以及代码可以分享一下嘛？感觉像是预处理时出现了问题。
> 
> 另外请问您测试用的模型是什么呢？如果您的相机型号不包含在我们公开的模型中，则您需要首先对您自己的数据集进行finetune。使用finetune后的网络进行测试

预训练的步骤按照：
1.通过bayer_to_npy.py将我的bggr数据转换成RGBG的数据
2.设置白电平（white point）为我的采集位数深度，然后进行归一化。（我采集的raw图没有带whtie point参数，所以人为设置了）

代码已经邮箱分享给您了。

测试的话我是自己先pretrain训练一次，然后用训练的模型测试的。这是因为我采集用的相机型号不在您公开的模型中，并且raw图计算出来的ratio range和您公开的模型差距较大，。

**Comment by Srameo** [comment]
1. 预处理的步骤需要先减去黑点平( $bl$ )之后，通过白电平( $wp$ )与 $bl$ 的差值进行归一化，即
    $$\frac{I-bl}{wp-bl}$$
2. 我看了下您的config，您确定您pretrain的`ratio_range`是正确的吗？因为看您展示的图像感觉ratio为1左右

**Comment by 0getworld** [comment]
> 1. 预处理的步骤需要先减去黑点平( bl )之后，通过白电平( wp )与 bl 的差值进行归一化，即
>    I−blwp−bl
> 2. 我看了下您的config，您确定您pretrain的`ratio_range`是正确的吗？因为看您展示的图像感觉ratio为1左右

1.这个我应该没有弄错，因为我只是在预处理阶段对wp做了这样的处理：
![image](https://github.com/Srameo/LED/assets/78095525/28675ec4-3502-44c2-ba97-1803a3349b98)

2.我采集了不同光照条件下的数据，按照您给的Additional Dgain计算公式应该没有问题。三种光照条件下的exp和iso情况：
![image](https://github.com/Srameo/LED/assets/78095525/dee62498-1de5-41ef-84ef-092b3c480649)

展示的图像是10-1lux下的

**Comment by Srameo** [comment]
1. 您的预处理操作没有问题。
2. 请问您在拍摄时在0.1lux环境下曝光时间是，gt的 $55425/1768=31$ 倍嘛？您sensor dump出的数据可能并不是线性关系，可能我们的计算方式并不适用。
3. 我们在 https://github.com/Srameo/LED/blob/main/docs/demo.md 中提到的 ratio 计算方式是为单反这类相机 capture 时使用的，您使用的sensor dump出的结果可能并不在提到的计算方式中。没有在文档中说明是我们的疏忽，之后我们会修改。

**Comment by 0getworld** [comment]
> 3\. https://github.com/Srameo/LED/blob/main/docs/demo.md

好的，这边清楚了，谢谢您！😄

**Comment by saalaman** [comment]
您好，我在fine-tune时出现了同样的问题，但是当迭代的次数增加的时候，颜色会慢慢恢复正常，我ccm直接用的sonyA7S2的标定ccm，数据集使用的是DRV。
![Uploading short_0017_1000.png…]()
![Uploading short_0017_10002.png…]()

**Comment by saalaman** [comment]
![short_0017_1000](https://github.com/Srameo/LED/assets/38523706/62f98d11-150c-437c-8157-7bb0db002790)
![short_0017_10002](https://github.com/Srameo/LED/assets/38523706/c95f9c04-a978-4d24-aa3c-f25dffcf9ecf)

**Comment by 0getworld** [comment]
> DRV

您好想问下你这个最终迭代次数是多少呢？

**Comment by saalaman** [comment]
不知道作者能不能解释一下这种现象，不太理解为什么会这样

**Comment by Srameo** [comment]
出现这种现象的原因**可能**是：我们预训练时使用的虚拟相机参数和您fine-tune时使用的相机（所拍摄的数据）相差过大。



> 但是当迭代的次数增加的时候，颜色会慢慢恢复正常



不过正如您所说，通常这种现象都可以通过增加fine-tune时的迭代数解决。

**Comment by PaoChaHuPao** [comment]
> > 请问您预处理数据的具体步骤以及代码可以分享一下嘛？感觉像是预处理时出现了问题。
> > 另外请问您测试用的模型是什么呢？如果您的相机型号不包含在我们公开的模型中，则您需要首先对您自己的数据集进行finetune。使用finetune后的网络进行测试
> 
> 预训练的步骤按照： 1.通过bayer_to_npy.py将我的bggr数据转换成RGBG的数据 2.设置白电平（white point）为我的采集位数深度，然后进行归一化。（我采集的raw图没有带whtie point参数，所以人为设置了）
> 
> 代码已经邮箱分享给您了。
> 
> 测试的话我是自己先pretrain训练一次，然后用训练的模型测试的。这是因为我采集用的相机型号不在您公开的模型中，并且raw图计算出来的ratio range和您公开的模型差距较大。

@0getworld 我想请教一下pretrain的步骤，不知道您还方便吗
