### ISSUE TITLE
repnr_nafnet训练后推理 报错Unexpected key(s) in state_dict 

### ISSUE THREAD

**Issue by create-li** [Srameo/LED#27]
你好，我在复现过程出现如下问题:
我使用repnr_nafnet.yaml 并修改了网络结构如下:
repnr_opt:
  dont_convert_module:
    - 'ending'
    - 'dwconv2'
    - 'downconv'
    - 'upconv'
  branch_num: 5
  align_opts:
    init_weight: 1.0
    init_bias: 0.0
network_g:
  type: NAFNet
  img_channel: 4
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 2
  dec_blk_nums: [2, 2, 2, 2]
训练完成之后，推理出现Unexpected key(s) in state_dict 错误，
 Unexpected key(s) in state_dict: "intro.main_weight", "intro.main_bias", "intro.align_weights.0", "intro.align_weights.1", "intro.align_weights.2", "intro.align_weights.3", "intro.align_weights.4", "intro.align_weights.5", "intro.align_biases.0", "intro.align_biases.1", "intro.align_biases.2", "intro.align_biases.3", "intro.align_biases.4", "intro.align_biases.5", "encoders.0.0.conv1.main_weight", "encoders.0.0.conv1.main_bias", "encoders.0.0.conv1.align_weights.0", "encoders.0.0.conv1.align_weights.1", "encoders.0.0.conv1.align_weights.2", "encoders.0.0.conv1.align_weights.3", "encoders.0.0.conv1.align_weights.4", "encoders.0.0.conv1.align_weights.5", "encoders.0.0.conv1.align_biases.0", "encoders.0.0.conv1.align_biases.1", "encoders.0.0.conv1.align_biases.2", "encoders.0.0.conv1.align_biases.3", "encoders.0.0.conv1.align_biases.4", "encoders.0.0.conv1.align_biases.5", "encoders.0.0.conv3.main_weight", "encoders.0.0.conv3.main_bias", "encoders.0.0.conv3.align_weights.0", "encoders.0.0.conv3.align_weights.1", "encoders.0.0.conv3.align_weights.2", "encoders.0.0.conv3.align_weights.3", "encoders.0.0.conv3.align_weights.4", "encoders.0.0.conv3.align_weights.5", "encoders.0.0.conv3.align_biases.0", "encoders.0.0.conv3.align_biases.1", "encoders.0.0.conv3.align_biases.2", "encoders.0.0.conv3.align_biases.3", "encoders.0.0.conv3.align_biases.4", "encoders.0.0.conv3.align_biases.5", "encoders.0.0.sca.1.main_weight", "encoders.0.0.sca.1.main_bias", "encoders.0.0.sca.1.align_weights.0", "encoders.0.0.sca.1.align_weights.1", "encoders.0.0.sca.1.align_weights.2", "encoders.0.0.sca.1.align_weights.3", "encoders.0.0.sca.1.align_weights.4", "encoders.0.0.sca.1.align_weights.5", "encoders.0.0.sca.1.align_biases.0", "encoders.0.0.sca.1.align_biases.1", "encoders.0.0.sca.1.align_biases.2", "encoders.0.0.sca.1.align_biases.3", "encoders.0.0.sca.1.align_biases.4", "encoders.0.0.sca.1.align_biases.5", "encoders.0.0.conv4.main_weight", "encoders.0.0.conv4.main_bias", "encoders.0.0.conv4.align_weights.0", "encoders.0.0.conv4.align_weights.1", "encoders.0.0.conv4.align_weights.2", "encoders.0.0.conv4.align_weights.3 .....
我对比了net的key和模型的key的数量和名称不一致。
不修改网络错误也会同样的错误。请问如何处理？谢谢

**Comment by Srameo** [comment]
请问您具体的推理命令以及yaml文件可以给出吗？

**Comment by create-li** [comment]
推理的yaml文件：
`repnr_opt:
  dont_convert_module:
    - 'ending'
    - 'dwconv2'
    - 'downconv'
    - 'upconv'
  branch_num: 5
  align_opts:
    init_weight: 1.0
    init_bias: 0.0

# network structures
network_g:
  type: NAFNet
  img_channel: 4
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 2
  dec_blk_nums: [2, 2, 2, 2]`

推理命令：python script/image_process.py -opt repnr_nafnet  。加上和不加--led错误内容都是一样。我测试了不修改网络结构也是训练后推理也是错误。而使用nafnet网络，修改和不修改网络结构推理都没有问题。

**Comment by Srameo** [comment]
在使用`image_process.py`脚本时，请直接使用nafnet的结构并在最后添加`--led`。请不要使用`repnr_nafnet`的结构。

**Comment by create-li** [comment]
嗯嗯，您的意思是①不要用repnr_nafnet的结构训练推理。还是说②使用repnr_nafnet结构的模型推理的使用yaml使用nafnet 但是要添加--led （这种我试过了不行）。我想应该是①第一个意思吧。

**Comment by Srameo** [comment]
> 推理命令：python script/image_process.py -opt repnr_nafnet 。加上和不加--led错误内容都是一样。我测试了不修改网络结构也是训练后推理也是错误。而使用nafnet网络，修改和不修改网络结构推理都没有问题。

您这里提到的"`而使用nafnet网络，修改和不修改网络结构推理都没有问题。`"是什么意思呢？

**Comment by create-li** [comment]
> 我其实是②的意思🥲
> 
> 您使用的checkpoint是怎么得到的呢？
基于repnr_nafnet.yaml 训练得到的，训练没有问题。推理会报key不一致的错误。

**Comment by create-li** [comment]
> > 推理命令：python script/image_process.py -opt repnr_nafnet 。加上和不加--led错误内容都是一样。我测试了不修改网络结构也是训练后推理也是错误。而使用nafnet网络，修改和不修改网络结构推理都没有问题。
> 
> 您这里提到的"`而使用nafnet网络，修改和不修改网络结构推理都没有问题。`"是什么意思呢？

您提供的network结构包括nafnet 和repnr_nafnet。就是我基于nafnet.yaml的配置训练和推理都没有问题，主要是排除我网络修改导致的问题。而使用repnr_nafnet推理时都会出现key不一致的错误，应该是不支持repnr结构推理吧？

**Comment by Srameo** [comment]
是的，目前并不支持repnr包装过的结构进行推理。但是由于我们使用了在线重参数化技术（[OREPA](https://github.com/JUGGHM/OREPA_CVPR2022)，CVPR2022），repnr包装的模型和重参数化后的模型性能完全一致。

**Comment by create-li** [comment]
嗯嗯，明白，谢谢您热心的解答
