### ISSUE TITLE
It seems something wrong with `python scripts/download_gdrive.py`

### ISSUE THREAD

**Issue by lizhogn** [Srameo/LED#4]
The current script itself relies on rawpy:
![image](https://github.com/Srameo/LED/assets/30550546/d07afad4-55ba-4c98-abfa-694fe4472773)

**Comment by lizhogn** [comment]
Commenting out these lines of code solves the problem above:
![image](https://github.com/Srameo/LED/assets/30550546/5b48e22f-4a71-479f-b710-785db6cc1b9d)

**Comment by lizhogn** [comment]
`Install.sh` lacks a command to put LIBRAW in /usr/local/lib (sudo make install), otherwise it will cause a error that RAWPY can't find libraw during installation
![image](https://github.com/Srameo/LED/assets/30550546/549d75b2-f0b9-4521-849e-7f23acc8ccae)
![image](https://github.com/Srameo/LED/assets/30550546/a687edf2-6441-4be5-82ea-ec210e0745f8)

**Comment by Srameo** [comment]
The `ImportError` was caused by a import command before we fully intalled the enviorment, which has been solved in commit https://github.com/Srameo/LED/commit/0b16687b2dc86d4677e7fcda46809abfae6b5d0b.

**Comment by Srameo** [comment]
Thanks for pointing out the bug on our install.sh! You could create a pull request for fixing that bug.

**Comment by Srameo** [comment]
We have fixed the bug on https://github.com/Srameo/LED/commit/ca6b7095ca758cd82f257b072ed1433dddce3a6c.
