### ISSUE TITLE
关于color bias的获取

### ISSUE THREAD

**Issue by 0getworld** [Srameo/LED#40]
想请教一下关于噪声模型中color bias是怎么获取的呢？我看您提供的标定代码中并无color bias的获取逻辑

**Comment by Srameo** [comment]
color bias 您可以通过对 dark frame (4, H, W) 取平均数得到 estimated_black_level (4, 1, 1)，之后使用 black_level - estimated_black_level 便可充当 color bias。该操作应该分别对不同 ISO 下的 dark frame 进行。

我们的标定代码并不能完全复现 ELD 中的噪声模型（原因是ELD并未开源其标定代码），只是一个简单的框架。

**Comment by ffmm123** [comment]
color bias ，这个参数对去噪的颜色有影响么？在建模噪声的过程中去掉该偏差，没有影响。
