### ISSUE TITLE
Inquiry Regarding Performance Discrepancy between LED and DNF Algorithms

### ISSUE THREAD

**Issue by e96031413** [Srameo/LED#5]
Dear @Srameo,

I am writing to you as I have come across your remarkable works, specifically "LED: Lighting Every Darkness in Two Pairs: A Calibration-Free Pipeline for RAW Denoising" and "DNF: Decouple and Feedback Network for Seeing in the Dark," and I am intrigued by the significant performance difference observed between the two algorithms.

To illustrate my query, I would like to reference the Sony split dataset from SID. In "LED's" Table 1, the LED algorithm achieves an impressive PSNR of 41.9842 and SSIM of 0.9539 for a 100x exposure. However, in "DNF's" Table 1, the DNF algorithm achieves a comparatively lower PSNR of 30.62 and SSIM of 0.797.

This stark contrast in performance has piqued my curiosity, and I am interested in understanding the factors that contribute to such a pronounced gap. It seems that the two algorithms might be tailored to address distinct tasks—one focusing on denoising exclusively, while the other perhaps incorporates a combination of Low-Light Image Enhancement (LLIE) and denoising.

Could you kindly shed some light on the underlying objectives and design philosophies of the LED and DNF algorithms? This clarification would greatly assist in deepening my comprehension of the nuances in your research.

Thank you for your time and consideration. I am genuinely fascinated by the advancements you have made in this field, and I am looking forward to enhancing my understanding of your work. Your expertise will undoubtedly contribute to my knowledge expansion.

I eagerly anticipate your response and thank you in advance for your assistance.

Best regards,

**Comment by Srameo** [comment]
Hi there! Thanks for your attention on our DNF and LED!

Please allow me to summarize your question:
Q1: What causes the difference between DNF and LED? and 
Q2: What's the objectives and design philosophies of the LED and DNF?

A1: The devil is in the color space. 
As for DNF, it focused on RAW-based low-light image **enhancement** which intends to get a vivid, clean and sharp sRGB output. Thus the metric is calculated on the output **RGB** image and the GT (sRGB).
As for LED, it focused on RAW-based low-light image **denoising** which intends to remove the noise on the input RAW image. Thus the metric is calculated on the output **RAW** image and the GT (RAW).

A2: Objectives has been demostrated in A1.
The design philosophies can be found in our paper: [DNF](https://openaccess.thecvf.com/content/CVPR2023/papers/Jin_DNF_Decouple_and_Feedback_Network_for_Seeing_in_the_Dark_CVPR_2023_paper.pdf) (paragraphs 2-4 of the introduction), and [LED](https://arxiv.org/abs/2308.03448) (paragraphs 3-4 of the introduction).

**Comment by e96031413** [comment]
Dear @Srameo,

I wanted to take a moment to express my heartfelt gratitude for your thoughtful response.

Your willingness to assist and your quick reply truly mean a lot to me.  Your insights and advice have provided me with the guidance I needed, and I am sincerely thankful for your generosity in sharing your knowledge and expertise.
