### ISSUE TITLE
LED_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth 模型测试报错

### ISSUE THREAD

**Issue by kaka36** [Srameo/LED#6]
用image_process或python scripts/benckmark.py \
    -t test \
    -p pretrained/network_g/LED_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth \
    --dataset SID SonyA7S2
 加载LED_Deploy_SID_SonyA7S2_CVPR20_Setting_Ratio100-300.pth 报错，错误为Missing key(s) in state_dict: "conv1_1.weight", "conv1_1.bias", "conv1_2.weight", "conv1_2.bias", "conv2_1.weight", "conv2_1.bias", "conv2_2.weight", "conv2_2.bias", "conv3_1.weight", "conv3_1.bias", "conv3_2.weight" ·······，是不是得从参数化之后采用用？

**Comment by kaka36** [comment]
对了，因为报错ModuleNotFoundError: No module named 'led.version'，我把version相关的都屏蔽掉了

**Comment by Srameo** [comment]
您好！

Q1: 使用脚本加载预训练模型时出现 Missing keys error，是否需要重参数化？
A1: 是的，加载模型需要使用重参数化的模型。但请参考我们的 Readme 文档https://github.com/Srameo/LED/blob/ca6b7095ca758cd82f257b072ed1433dddce3a6c/README.md?plain=1#L158
在运行脚本时增加 `--led` 选项便可加载重参数化后的网络模型。

Q2: ModuleNotFoundError: No module named 'led.version'
A2: 请问可以知道您安装 LED 时候执行了我们的脚本 `install.sh` 吗？如果没有的话，请问可否提供下您配置环境时的具体操作吗？这可能对我们找出bug有很大帮助。

感谢您对LED的关注！

**Comment by kaka36** [comment]
谢谢，Q1可以加载了，抱歉对Python不是很熟悉。
Q2：没有按照 install.sh脚本进行环境配置，之前安装的环境，提示缺什么就装什么，没有具体的步骤，屏蔽掉version可以用不影响好像。
