### ISSUE TITLE
多卡训练问题

### ISSUE THREAD

**Issue by WoodmanLiu** [Srameo/LED#9]
您好！我在训练LED的时候出现的单张显卡显存不够的情况，请问如何设置多卡训练？

**Comment by Srameo** [comment]
请问可以提供下您多卡训练运行的命令以及错误信息吗？

**Comment by WoodmanLiu** [comment]
我将num_gpu设置为1，batch_size_per_gpu设置为16时可以运行，但是设置为32时就会显存不够。因此我将num_gpu改为2，batch_size_per_gpu改为16，请问这样可以达到单卡(如果显存够)batch_size=32一样的效果吗？

**Comment by Srameo** [comment]
理论上来讲，效果会差不多。不过我们也没有实验过，因此不能给您一个定论
